apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.nexusNs }}
---
{{- if .Values.externaldns.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.externaldnsNs }}
{{- end }}
---
